# Yarn Classic configuration for FlyRancher Pro
--install.prefer-offline true
--install.silent false  
--install.frozen-lockfile true
--network-timeout 100000
--network-concurrency 1
--cache-folder .yarn-cache
--disable-self-update-check true
