name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches: [ main, master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm audit --audit-level=high || echo "⚠️ Security audit found issues"
      
      - name: Build application
        run: |
          npm run build
        env:
          NODE_ENV: production
          VITE_APP_ENV: production
          VITE_API_BASE_URL: https://flyrancher-sub.onrender.com
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
          retention-days: 1

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Health check job
  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    
    steps:
      - name: Wait for deployment
        run: sleep 30
      
      - name: Health check
        run: |
          # Check if the site is accessible
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://samuelrdc69.github.io/flyrancher-pro-frontend/)
          
          if [ $HTTP_STATUS -eq 200 ]; then
            echo "✅ Site is accessible (HTTP $HTTP_STATUS)"
          else
            echo "❌ Site is not accessible (HTTP $HTTP_STATUS)"
            exit 1
          fi
          
          # Check if essential resources load
          curl -f https://samuelrdc69.github.io/flyrancher-pro-frontend/manifest.json > /dev/null || echo "⚠️ Manifest file not found"
          echo "✅ Basic health check completed"
          
      - name: Lighthouse CI
        run: |
          if command -v npm &> /dev/null; then
            npm install -g @lhci/cli@0.12.x || echo "⚠️ Failed to install Lighthouse CI"
            
            # Run Lighthouse audit
            lhci autorun --config='{
              "ci": {
                "collect": {
                  "url": ["https://samuelrdc69.github.io/flyrancher-pro-frontend/"],
                  "numberOfRuns": 1
                },
                "assert": {
                  "assertions": {
                    "categories:performance": ["warn", {"minScore": 0.8}],
                    "categories:accessibility": ["error", {"minScore": 0.9}],
                    "categories:best-practices": ["warn", {"minScore": 0.8}],
                    "categories:seo": ["warn", {"minScore": 0.8}],
                    "categories:pwa": ["warn", {"minScore": 0.8}]
                  }
                }
              }
            }' || echo "⚠️ Lighthouse audit failed or completed with warnings"
          else
            echo "⚠️ npm not available, skipping Lighthouse audit"
          fi

  # Notification job
  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy, health-check]
    if: always()
    
    steps:
      - name: Deployment Success Notification
        if: ${{ needs.deploy.result == 'success' && needs.health-check.result == 'success' }}
        run: |
          echo "🚀 Deployment successful!"
          echo "📱 Site URL: https://samuelrdc69.github.io/flyrancher-pro-frontend/"
          echo "✅ Health check passed"
      
      - name: Deployment Failure Notification  
        if: ${{ needs.deploy.result == 'failure' || needs.health-check.result == 'failure' }}
        run: |
          echo "❌ Deployment or health check failed"
          echo "🔍 Check the logs for details"
          exit 1

  # Security job
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run security audit
        run: |
          npm audit --audit-level=moderate || echo "⚠️ Security vulnerabilities found"
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'
